version: '3.9'
services:
  test:
    build: .
    image: qqchat-bot:latest
    restart: always
    ports:
      - 5900:5900
    environment:
      - ENABLED_X11VNC=yes
    volumes:
      - ./data:/bot/data
      - ./amr:/bot/amr
      - ./src:/bot/src
      - ./demos:/bot/demos
    extra_hosts:
      - "master.io:10.0.20.17"
