#FROM bincooo/chrome-vnc:latest
#FROM debian:bullseye-slim
FROM node:18-slim

ADD . /app
ADD Enter /usr/local/bin
RUN chmod +x /usr/local/bin/Enter
RUN chmod +x /app/docker-entrypoint.sh
RUN chmod +x /app/qqchat-bot-linux
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
RUN sed -i s/deb.debian.org/mirrors.tencent.com/g /etc/apt/sources.list

RUN apt-get update \
  && apt-get install -y make gcc g++ \
  && rm -rf /var/lib/apt/lists/*

RUN npm i -g wx-voice
RUN npm i -g ffmpeg-static@^4.4.1
ENTRYPOINT ["/bin/bash", "/app/docker-entrypoint.sh"]