version: '3.9'
services:
  test:
    build: .
    image: qqchat-bot:latest
    restart: always
    ports:
      - 5900:5900
    environment:
      - ENABLED_X11VNC=yes
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./demos:/app/demos
      - ./preset.json:/app/preset.json
    extra_hosts:
      - "master.io:10.0.20.17"
